In [ ]:
!pip install matplotlib seaborn

In [1]:
import pandas as pd



df = pd.read_csv("../data/Financial_inclusion_dataset.csv")

# Aperçu rapide
df.head()

,country,year,uniqueid,Has a Bank account,Type of Location,Cell Phone Access,household_size,Respondent Age,gender_of_respondent,The relathip with head,marital_status,Level of Educuation,Type of Job
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3.0,24.0,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5.0,70.0,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5.0,26.0,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5.0,34.0,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8.0,26.0,Male,Child,Single/Never Married,Primary education,Informally employed

In [2]:
# Taille du dataset
print(df.shape)

# Colonnes et types
print(df.info())

# Statistiques descriptives pour les colonnes numériques
print(df.describe())

(23524, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23510 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   Has a Bank account      23488 non-null  object
 4   Type of Location        23509 non-null  object
 5   Cell Phone Access       23513 non-null  object
 6   household_size          23496 non-null  float64
 7   Respondent Age          23490 non-null  float64
 8   gender_of_respondent    23490 non-null  object
 9   The relathip with head  23520 non-null  object
 10  marital_status          23492 non-null  object
 11  Level of Educuation     23495 non-null  object
 12  Type of Job             23494 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 2.3+ MB
None
               year  household_size  Respondent Age
count  23524.000000    23496.000000    23490.000000
mean    2016.979000        3.681818       38.804300
std        0.899669        2.279933       16.519996
min     2016.000000        0.000000       16.000000
25%     2016.000000        2.000000       26.000000
50%     2017.000000        3.000000       35.000000
75%     2018.000000        5.000000       49.000000
max     2056.000000       21.000000      100.000000

In [3]:
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

country                   14
Has a Bank account        36
Type of Location          15
Cell Phone Access         11
household_size            28
Respondent Age            34
gender_of_respondent      34
The relathip with head     4
marital_status            32
Level of Educuation       29
Type of Job               30
dtype: int64

In [4]:
# Colonnes numériques
num_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

# Colonnes catégorielles
cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

num_cols, cat_cols

(['year', 'household_size', 'Respondent Age'],
 ['country',
  'uniqueid',
  'Has a Bank account',
  'Type of Location',
  'Cell Phone Access',
  'gender_of_respondent',
  'The relathip with head',
  'marital_status',
  'Level of Educuation',
  'Type of Job'])

In [5]:
for col in num_cols:
    if df[col].isnull().sum() > 0:
        median = df[col].median()
        df[col].fillna(median, inplace=True)

In [6]:
for col in cat_cols:
    if df[col].isnull().sum() > 0:
        df[col].fillna("Unknown", inplace=True)

In [7]:
# Vérification finale des NaN
df.isnull().sum().sum()

np.int64(0)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   Has a Bank account      23524 non-null  object
 4   Type of Location        23524 non-null  object
 5   Cell Phone Access       23524 non-null  object
 6   household_size          23524 non-null  float64
 7   Respondent Age          23524 non-null  float64
 8   gender_of_respondent    23524 non-null  object
 9   The relathip with head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  Level of Educuation     23524 non-null  object
 12  Type of Job             23524 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 2.3+ MB

,country,year,uniqueid,Has a Bank account,Type of Location,Cell Phone Access,household_size,Respondent Age,gender_of_respondent,The relathip with head,marital_status,Level of Educuation,Type of Job
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3.0,24.0,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5.0,70.0,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5.0,26.0,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5.0,34.0,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8.0,26.0,Male,Child,Single/Never Married,Primary education,Informally employed

In [10]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64
 2   uniqueid                23524 non-null  object
 3   has_a_bank_account      23524 non-null  object
 4   type_of_location        23524 non-null  object
 5   cell_phone_access       23524 non-null  object
 6   household_size          23524 non-null  float64
 7   respondent_age          23524 non-null  float64
 8   gender_of_respondent    23524 non-null  object
 9   the_relathip_with_head  23524 non-null  object
 10  marital_status          23524 non-null  object
 11  level_of_educuation     23524 non-null  object
 12  type_of_job             23524 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 2.3+ MB

In [13]:
df.to_csv("../data/financial_inclusion_clean.csv", index=False)